!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  process_comment_data: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - comments_processed.csv
    task_name: process_comment_data
    task_out: output
enabled: true
language: Python
src_files:
- label_comment_emotion_concepts.py
target_dir: label_comment_emotion_concepts
