!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  merge_labelled_channel_data: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - channels_merged_labelled_text.csv
    task_name: merge_labelled_channel_data
    task_out: output
enabled: true
language: Python
src_files:
- analyze_channel_text.py
target_dir: analyze_channel_text
