!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  label_comment_topics: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - comments_topic_info.csv
    task_name: label_comment_topics
    task_out: output
  merge_labelled_comment_data: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - comments_merged_labelled_text.csv
    task_name: merge_labelled_comment_data
    task_out: output
  process_channel_data: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - channels_processed.csv
    task_name: process_channel_data
    task_out: output
enabled: true
language: Python
src_files:
- construct_comment_networks.py
target_dir: construct_comment_networks
