!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  construct_comment_networks: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - comments_Microsoft Research_mention_network.gt
    - comments_Talks at Google_mention_network.gt
    task_name: construct_comment_networks
    task_out: output
enabled: true
language: Python
src_files:
- model_comment_networks.py
target_dir: model_comment_networks
