!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  _import_: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - config.yaml
    task_name: _import_
    task_out: ./
  collect_channel_data: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - EuroPythonConference.json
    - MicrosoftResearch.json
    - PyDataTV.json
    - datasocietyresearchinstitu1085.json
    - talksatgoogle.json
    task_name: collect_channel_data
    task_out: output
enabled: true
language: Python
src_files:
- process_channel_data.py
target_dir: process_channel_data
