!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  merge_labelled_comment_data: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - comments_merged_labelled_text.csv
    task_name: merge_labelled_comment_data
    task_out: output
enabled: true
language: Python
src_files:
- analyze_comment_text.py
target_dir: analyze_comment_text
