!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  process_channel_data: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - channels_processed.csv
    task_name: process_channel_data
    task_out: output
enabled: true
language: Python
src_files:
- label_channel_topics.py
target_dir: label_channel_topics
