!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  label_channel_topics: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - channels_topic_info.csv
    task_name: label_channel_topics
    task_out: output
  merge_labelled_channel_data: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - channels_merged_labelled_text.csv
    task_name: merge_labelled_channel_data
    task_out: output
enabled: true
language: Python
src_files:
- construct_channel_networks.py
target_dir: construct_channel_networks
