!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  detect_comment_language: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - comments_predicted_language.csv
    task_name: detect_comment_language
    task_out: output
  process_comment_data: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - comments_processed.csv
    task_name: process_comment_data
    task_out: output
enabled: true
language: Python
src_files:
- filter_or_translate_comments.py
target_dir: filter_or_translate_comments
